# Site settings
title: UNIS-UN
url: http://www.unis-un.org
email: info@unis-un.org
description: "UNIS-UN  is an annual, international, student led conference held in the General Assembly on the United Nations"
logo_url: http://www.unis-un.org/img/fb.png
#Upcoming Conference year (Remember to use quotes)
conf_year: "2017"

#Settings
show_tweets: false
show_sched: false
show_workingpaper: false
live: false

# Social media
twitter_username: unis_un
facebook_username: unisunconf
insta_username: unisun_nyc

# Build settings
markdown: kramdown
permalink: pretty

# Jekyll plugins
gems:
  - jekyll-redirect-from
